version: '3'
services:
  player-mysql:
    image: mysql:latest
    network_mode: host
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cplayerdb
      MYSQL_USER_NAME: root
      MYSQL_PASSWORD: root
  userapp:
    image: 8380084032/userapp/user-app
    build: userservice/
    restart: always
    network_mode: host
    container_name: userapp-docker
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
    - player-mysql
  playerapp:
    image: 8380084032/playerapp/player-app
    build: favouriteservice/
    restart: always
    network_mode: host
    container_name: playerspring-docker
    ports:
      - 8082:8082
    expose:
      - 8082
    depends_on:
    - player-mysql
  angular:
    image: 8380084032/playerappui/angular-image
    build: CPlayersUI/
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
    expose:
      - 4200

